# Generated by Django 4.2.26 on 2025-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Bioma',
                'verbose_name_plural': 'Biomas',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('biomes', models.ManyToManyField(related_name='trees', to='app.biome')),
            ],
            options={
                'verbose_name': 'Árvore',
                'verbose_name_plural': 'Árvores',
            },
        ),
    ]
