# Generated by Django 5.2.8 on 2025-11-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeBiome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biome_trees', to='app.biome')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_biomes', to='app.tree')),
            ],
            options={
                'verbose_name': 'Árvore por Bioma',
                'verbose_name_plural': 'Árvores por Bioma',
                'db_table': 'tree_biomes',
                'unique_together': {('tree', 'biome')},
            },
        ),
    ]
